config/routes.rb
Twice::Application.routes.draw do
  resources :tweets do
    collection do
      get 'import_csv_new'
      post 'import_csv'
      get 'archives/:yyyymm', :action => :archives, :as =>'archives'
      get 'search', :action => :search, :as =>'search'
    end
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  root :to => 'home#index'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  

end

app/models/tweet.rb
# coding: utf-8
require 'csv'   # csv操作を可能にするライブラリ
require 'kconv' # 文字コード操作をおこなうライブラリ

class Tweet < ActiveRecord::Base
  
  belongs_to :user
  
  def self.import_csv(csv_file,user)
    # csvファイルを受け取って文字列にする
    csv_text = csv_file.read

    # 読み込む前に古いツイートをすべて削除する。
    user.tweet.delete_all

    #文字列をUTF-8に変換
    CSV.parse(Kconv.toutf8(csv_text)) do |row|

      # ヘッダー行を回避するためにtweet_idが数値でない場合は読み飛ばす
      if row[0] =~ /\A\d+\z/
        tweet = Tweet.new

        tweet.tweet_id              = row[0]
        tweet.in_reply_to_status_id = row[1]
        tweet.in_reply_to_user_id   = row[2]
        tweet.timestamp             = row[3]
        tweet.source                = row[4]
        tweet.text                  = row[5]
        tweet.retweeted_status_id   = row[6]
        tweet.retweeted_status_user_id    = row[7]
        tweet.retweeted_status_timestamp  = row[8]
        tweet.expanded_urls         = row[9]
        tweet.user_id = user.id
        
        tweet.save

      end

    end
    return true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :trackable, :omniauthable
  
  has_many :tweet, dependent: :destroy
  
  def self.find_for_twitter_oauth(auth)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.info.nickname,
                          provider:auth.provider,
                          uid:auth.uid,
                          password:Devise.friendly_token[0,20]
                          )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to tweets_path
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/tweets_controller.rb
# coding: utf-8

class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  before_action :set_user
  before_action :make_archive

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = @user.tweet.order(:id).page params[:page]
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
  
  # GET /tweets/import_csv_new
  def import_csv_new
  end  

  # POST /tweets/import_csv
  def import_csv
    respond_to do |format|
      if Tweet.import_csv(params[:csv_file],current_user)
        format.html { redirect_to tweets_path }
        format.json { head :no_content }
      else
        format.html { redirect_to tweets_path, :notice => "CSVファイルの読み込みに失敗しました。" }
        format.json { head :no_content }
      end
    end
  end  
  
  # GET /tweets/archives/201402
  def archives
    @tweets = @user.tweet
             .where("strftime('%Y%m', tweets.timestamp) = '"+params[:yyyymm]+"'")
             .order(:id)
             .page params[:page]
  end  
  
  # GET /tweets/search/keyword
  def search
    @tweets = @user.tweet
             .search(:text_cont => params[:q]).result
             .order(:id)
             .page params[:page]
  end  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet_id, :in_reply_to_status_id, :in_reply_to_user_id, :timestamp, :source, :text, :retweeted_status_id, :retweeted_status_user_id, :retweeted_status_timestamp, :expanded_urls)
    end
    
    # ユーザがログインしていなければ、ホームにリダイレクト
    def check_user
      unless user_signed_in?
        redirect_to :root
      end
    end
    
    # アーカイブ見出し作成
    def make_archive
      @archives = @user.tweet.group("strftime('%Y%m', tweets.timestamp)")
                             .order("strftime('%Y%m', tweets.timestamp) desc")
                             .count
    end
    
    # インスタンス変数にログイン中のユーザをセット
    def set_user
      @user = current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
# coding: utf-8
module TweetsHelper
  def ymconv(yyyymm,cnt=nil)
    yyyy = yyyymm[0,4]
    mm = yyyymm[4,2]
    
    if cnt == nil
      return yyyy + "年" + mm + "月 "
    else
      return yyyy + "年" + mm + "月 (" + cnt + ")"
    end
    
  end
end

app/views/home/index.html.erb
<h1>Twiceへようこそ</h1>
<p>ログインして利用を開始しましょう</p>
<%= link_to (user_omniauth_authorize_path :twitter), class: "btn btn-large btn-primary" do %>
   Twitterでログイン
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twice" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Twice</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "ログアウト", (destroy_user_session_path)  %></li>
              <% else %>
                <li><%= link_to "ログイン", (user_omniauth_authorize_path :twitter)  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twice" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Twice</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "ログアウト", (destroy_user_session_path)  %></li>
              <% else %>
                <li><%= link_to "ログイン", (user_omniauth_authorize_path :twitter)  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/tweets.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twice" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href=<%= root_path %>>Twice</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "ログアウト", (destroy_user_session_path)  %></li>
              <% else %>
                <li><%= link_to "ログイン", (user_omniauth_authorize_path :twitter)  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Search</li>
              <%= form_tag(search_tweets_path, :method => "get") do %>
                <div class="input-append">
                  <%= text_field_tag("q", params[:q], :class => "span9") %>
                  <%= submit_tag "検索", :class => "btn"%>
                </div>
              <% end %>
              <li class="nav-header">Archives</li>
              <% @archives.each do |yyyymm, count| %>
              <li><%= link_to ymconv(yyyymm, count.to_s) , archives_tweets_path(:yyyymm => yyyymm)%><li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.text_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_status_id %><br>
    <%= f.text_field :in_reply_to_status_id %>
  </div>
  <div class="field">
    <%= f.label :in_reply_to_user_id %><br>
    <%= f.text_field :in_reply_to_user_id %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_area :source %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :retweeted_status_id %><br>
    <%= f.text_field :retweeted_status_id %>
  </div>
  <div class="field">
    <%= f.label :retweeted_status_user_id %><br>
    <%= f.text_field :retweeted_status_user_id %>
  </div>
  <div class="field">
    <%= f.label :retweeted_status_timestamp %><br>
    <%= f.datetime_select :retweeted_status_timestamp %>
  </div>
  <div class="field">
    <%= f.label :expanded_urls %><br>
    <%= f.text_field :expanded_urls %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweets">
  <p class="tweet-text"><%= tweet.text %></p>
  <p class="tweet-date"><%= tweet.timestamp.strftime("%Y-%m-%d %H:%M:%S") %></p>
</div>

app/views/tweets/archives.html.erb
<h1><%= ymconv(params[:yyyymm]) %>のツイート一覧</h1>

<%= render(@tweets) %>
<% if @tweets.count == 0 %>
  <p><%= ymconv(params[:yyyymm]) %> のツイートはありません</p>
<% end %>
<%= paginate (@tweets) %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/import_csv_new.html.erb
<h1>Import tweets CSV File</h1>
<%= form_tag('import_csv', :method => 'post', :multipart => true, :class => 'navbar-form pull-left') do %>
    <%= file_field_tag(:csv_file) %>
    <%= submit_tag("CSV Import",:class => 'btn') %>
<% end %>

app/views/tweets/index.html.erb
<h1>ツイート一覧</h1>

<%= render(@tweets) %>

<%= paginate (@tweets) %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/search.html.erb
<h1>「<%= params[:q] %>」の検索結果</h1>

<%= render(@tweets) %>
<% if @tweets.count == 0 %>
  <p><%= params[:q] %>に一致するツイートはありませんでした。</p>
<% end %>
<%= paginate (@tweets) %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet_id %>
</p>

<p>
  <strong>In reply to status:</strong>
  <%= @tweet.in_reply_to_status_id %>
</p>

<p>
  <strong>In reply to user:</strong>
  <%= @tweet.in_reply_to_user_id %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @tweet.timestamp %>
</p>

<p>
  <strong>Source:</strong>
  <%= @tweet.source %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Retweeted status:</strong>
  <%= @tweet.retweeted_status_id %>
</p>

<p>
  <strong>Retweeted status user:</strong>
  <%= @tweet.retweeted_status_user_id %>
</p>

<p>
  <strong>Retweeted status timestamp:</strong>
  <%= @tweet.retweeted_status_timestamp %>
</p>

<p>
  <strong>Expanded urls:</strong>
  <%= @tweet.expanded_urls %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>